apiVersion: v2
name: search-api
description: A Helm chart for deploying the search API wrapper

# Application chart
type: application

# Chart version
version: 0.1.0

# Application version
appVersion: "1.0.0"
