replicaCount: 1
repository: ghcr.io/aureliusenterprise/m4i-atlas-rest-api
pullPolicy: Always
service:
  name: reverse-proxy
  type: ClusterIP
  externalPort: 5000
  internalPort: 5000
env:
  elastic_username: elastic
  elastic_host: https://elastic-search-es-http:9200
  elastic_ca_certs_path: "/secret_certs/ca.crt"
elastic_secret_crt_name: elastic-search-es-http-certs-public
