[tool.poetry]
name = "m4i-search-api"
version = "0.1.0"
description = "API wrapper for Elastic App Search secured with Atlas user auth"
authors = ["Aurelius Enterprise <info@aureliusenterprise.com>"]
license = "UNLICENSED"
readme = "README.md"

[[tool.poetry.packages]]
include = "m4i_search_api"

[tool.poetry.dependencies]
python = "~3.8"
flask = "2.1.2"
gunicorn = "^22.0.0"
requests = "^2.32.3"
pytest = "^7.4.4"

[tool.poetry.dependencies.m4i-backend-core]
path = "../../libs/m4i-backend-core"
develop = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
